config/routes.rb
Rails.application.routes.draw do
  get 'credit/show'
  devise_for :users, controllers: {seessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'accounts', to: 'users/registrations#new_account'
    post 'accounts', to: 'users/registrations#create_account'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items, only: [:index]
  get 'items/sell'
  resources :users, only: [:show, :edit, :update]
  resources :items do
    collection do #最終的にmemberに切り替える
      get :confirmation

      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :homes, only: [:new]
  resources :credit, only: [:new, :show, :destroy] do
    collection do
      post :pay
      post :delete
      get :show
      get :buy
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  #買った商品、現在売っている商品、すでに売った商品を取り出すため
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :saling_items, -> { where("buyer_id is NULL") }, foreign_key: "saler_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "saler_id", class_name: "Item"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :nickname
    validates :password
    validates :birthday
    validates :hurigana_first
    validates :hurigana_family
    validates :first_name
    validates :family_name
  end
  with_options format: {with: /\A[ぁ-んー－]+\z/, message: "は全角ひらがなで入力してください"} do
    validates :hurigana_first, allow_blank: true
    validates :hurigana_family, allow_blank: true
  end

  with_options format: {with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角で入力してください"} do
    validates :first_name, allow_blank: true
    validates :family_name, allow_blank: true
  end

  has_one :account
  has_one :address
  has_one :credit
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def sign_up_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :first_name, :family_name, :hurigana_first, :hurigana_family, :birthday)
  end

  def address_params
    params.require(:address).permit(:shipping_first_name, :shipping_family_name, :shipping_hurigana_first, :shipping_hurigana_family, :zipcode, :prefecture_id, :city, :address, :others, :phone_number)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def show
  end

  def update
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.UserDetails
  .UserDetails__inner
    .UserDetails__config
      %ul
        %li.UserDetails__left-box
          .UserDetails__parent
            = link_to edit_user_path, class: "UserDetails__child" do
              プロフィール変更
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              いいね一覧
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              出品する
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              出品一覧
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              出品売却済
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              購入一覧
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              発送元・お届け先住所変更
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              クレジットカード登録
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to destroy_user_session_path, data: { confirm: "本当にログアウトします？"}, method: :delete, class: "UserDetails__child logout" do
              ログアウト
              = icon('fas', 'caret-right', class: "UserDetails__icon")

    .UserDetails__mypage
      = form_with model: @user do |f|
        %h1.UserDetails__profile プロフィール
        .UserDetails__right-box
          = image_tag("/images/sea.jpeg", alt: "ヘッダー", class: "UserDetails__img")
          .UserDetails__postion
            = image_tag("/images/fox.jpeg", size: "100x100", alt: "ヘッダー", class: "UserDetails__icon")
            = f.label :nickname, class: "UserDetails__hidden"
            = f.text_field :nickname, placeholder: "例)foxセール中", class: "UserDetails__edit"
        .UserDetails__show-box
          %h1.UserDetails__show-title
          %p.UserDetails__show-text キ狭義にはキツネ属のことである[1][2]。広義には、明確な定義はないがイヌ亜科の数属を総称する[3][4]が、これは互いに近縁でない属からなる多系統である。
          最も狭義にはキツネ属の1種アカギツネのことである[5][6]。古来、日本で「狐」といえば、アカギツネの亜種ホンドギツネのことだったが、蝦夷地進出後は、北海道の別亜種キタキツネも含むようになった。
          ただし、この記事では広義のキツネを扱うものとする。キツネ属、アカギツネについてはそれぞれの記事を参照。
          = f.submit "変更する", class: 'UserDetails__btn'

app/views/users/show.html.haml
.Header
  .Header__inner
    .Header__logo-search
      .Header__logo
        = link_to image_tag("/images/logo.png", alt: "furima", class: "Header__logo-inner"), "#"
.UserDetails
  .UserDetails__inner
    .UserDetails__config
      %ul
        %li.UserDetails__left-box
          .UserDetails__parent
            = link_to edit_user_path, class: "UserDetails__child" do
              プロフィール変更
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              いいね一覧
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              出品する
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              出品一覧
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              出品売却済
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              購入一覧
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to '/', class: "UserDetails__child" do
              発送元・お届け先住所変更
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to new_credit_path, class: "UserDetails__child" do
              クレジットカード登録/詳細
              = icon('fas', 'caret-right', class: "UserDetails__icon")
          .UserDetails__parent
            = link_to destroy_user_session_path, data: { confirm: "本当にログアウトします？"}, method: :delete, class: "UserDetails__child logout" do
              ログアウト
              = icon('fas', 'caret-right', class: "UserDetails__icon")

    .UserDetails__mypage
      %h1.UserDetails__profile プロフィール
      .UserDetails__right-box
        = image_tag("/images/sea.jpeg", alt: "ヘッダー", class: "UserDetails__img")
        .UserDetails__postion
          = image_tag("/images/fox.jpeg", size: "100x100", alt: "ヘッダー", class: "UserDetails__icon")
        .UserDetails__user-name キツネ
      .UserDetails__show-box
        %h1.UserDetails__show-title
        %p.UserDetails__show-text キ狭義にはキツネ属のことである[1][2]。広義には、明確な定義はないがイヌ亜科の数属を総称する[3][4]が、これは互いに近縁でない属からなる多系統である。
        最も狭義にはキツネ属の1種アカギツネのことである[5][6]。古来、日本で「狐」といえば、アカギツネの亜種ホンドギツネのことだったが、蝦夷地進出後は、北海道の別亜種キタキツネも含むようになった。
        ただし、この記事では広義のキツネを扱うものとする。キツネ属、アカギツネについてはそれぞれの記事を参照。

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml