config/routes.rb
Rails.application.routes.draw do
  get 'credit/show'
  devise_for :users, controllers: {seessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'accounts', to: 'users/registrations#new_account'
    post 'accounts', to: 'users/registrations#create_account'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items, only: [:index]
  get 'items/sell'
  resources :users, only: [:show, :edit, :update]
  resources :items do
    collection do #最終的にmemberに切り替える
      get :confirmation

      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :homes, only: [:new]
  resources :credit, only: [:new, :show, :destroy] do
    collection do
      post :pay
      post :delete
      get :show
      get :buy
    end
  end
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_controller.rb
class CreditController < ApplicationController
  before_action :set_card, only: [:show, :delete]

  def pay
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
    if params['payjpToken'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        card: params['payjpToken'],
        metadata: {user_id: current_user.id}
      )
      @card = Credit.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: :show
        flash[:notice] = 'クレジットカードの登録が完了しました'
      else
        redirect_to action: "pay"
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end  

  def new
    card = Credit.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end
  
  def show
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
    end
  end
    
  def buy
    if @card.blank?
      redirect_to action: "new"
      flash[:alert] = '購入にはクレジットカード登録が必要です'
    else
      @product = Product.find(params[:product_id])
      card = current_user.credit_card
      Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      Payjp::Charge.create(
        amount: @product.price,
        customer: card.customer_id,
        current: 'jpy',
      )
      if @product.update(status: 1, buyer_id: current_user.id)
        flash[:notice] = '購入しました。'
        redirect_to controller: "items", action: 'show'
      else
        flash[:alert] = '購入に失敗しました。'
        redirect_to controller: "items", action: 'show'
      end
    end
  end
      
  def delete
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      flash[:notice] = 'クレジットカードを削除しました。購入の際は再度登録をお願いいたします。'
      redirect_to root_path
    end
  end
  
  private

  def set_card
    @card = current_user.credit
  end
end

app/helpers/credit_helper.rb
module CreditHelper
end

app/views/credit/new.html.haml
.Credit-Wrapper
  %p.Credit-Wrapper__title= "クレジットカード情報を入力"
  = form_tag(pay_credit_index_path, mehotd: :post, id: 'charge-form', name: "inputForm", class: "Credit-Wrapper__form") do
    %span.charge-errors
    .Register-Inner

      .Register-Inner__form
        %span.Register-Inner__label カード番号
        %span.Register-Inner__require 必須
        %input.Register-Inner__input-number.number.input-default{maxlength: "16", name: "number", placeholder: "カード番号", type: "text", id: "payment_card_no"}/
        = image_tag("/images/credit-groups.png", class:"Register-Inner__cards")

      .Register-Inner__select
        %span.Register-Inner__label 有効期限
        %span.Register-Inner__require 必須
        .Register-Inner__selects
          .Register-Inner__month
            %select.exp_month#payment_expiration_date_1i{maxlength: "2", name: "exp_month", type: "text"}
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %text.expiration_date_box__text 月

          .Register-Inner__year
            %select.exp_year#payment_expiration_date_2i{maxlength: "4", name: "exp_year", type: "text"}
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %text.expiration_date_box__text 年

      .Register-Inner__security
        %span.Register-Inner__label セキュリティー番号
        %span.Register-Inner__require 必須
        %input.Register-Inner__input-security.cvc.input-default{maxlength: "3", name: "cvc", placeholder: "カード背面４桁もしくは３桁の番号", type: "text", id: "payment_card_cvc"}
        .Register-Inner__card-info
          = link_to "?カード裏面の番号とは", "#"
      .actions
        %button.register-member#submit-button{type: "submit"} 登録完了
  //後ほど参考にするために一時的にコメントアウト
  -# = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"
  -# %select#exp_month.vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month{name: "exp_month", type: "text"}
  -#   %option{value: ""} --
  -#   - 12.times do |index|
  -#     %option{value: "#{index + 1}"}= "#{index + 1}"
  -# %span 月

  -# %select#exp_year.vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year{name: "exp_year", type: "text"}
  -#   %option{value: ""} --
  -#   - 10.times do |index|
  -#     %option{value: "#{index + 19}"}= "#{index + 19}"
  -#   -# <i class="fas fa-chevron-down"></i>
  -# %span 年
  -# = text_field_tag "cvc", "", class: "cvc .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year__age__security__security-code__security-flame", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
  -# = submit_tag "追加する", id: "token_submit"

app/views/credit/news.html.haml
.entry-main
.blank
= form_tag(pay_credit_index_path, mehotd: :post, id: 'charge-form', name: "inputForm") do
  .vacuum
    .vacuum__wide-box
      .vacuum__wide-box__entry-header
        クレジットカード情報を入力
      .vacuum__wide-box__entry-header__entry-box
        .vacuum__wide-box__entry-header__entry-box__entry-form
          .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register
            カード番号
          .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want
            必須
          = text_field_tag "number", "", class: "number .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"
          .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest
            -# = image_tag("/images/visa.svg", size: "49x20", alt: "visa.tag", class: "crest")
            -# = image_tag("/images/master-card.svg", size: "34x20", alt: "master.tag", class: "crest")
            -# = image_tag("/images/saison-card.svg", size: "30x20", alt: "saison.tag", class: "crest")
            -# = image_tag("/images/jcb.svg", size: "32x20", alt: "jcb.tag", class: "crest")
            -# = image_tag("/images/american_express.svg", size: "21x20", alt: "american_express.tag", class: "crest")
            -# = image_tag("/images/dinersclub.svg", size: "32x20", alt: "dinersclub.tag", class: "crest")
            -# = image_tag("/images/discover.svg", size: "32x20", alt: "discover.tag", class: "crest")
          .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration
            .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register
              有効期限
            .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want
              必須
            .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days
              .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm
                %select#exp_month.vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  - 12.times do |index|
                    %option{value: "#{index + 1}"}= "#{index + 1}"
                  -# <i class="fas fa-chevron-down"></i>
              .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__spell
                月
              .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy
                %select#exp_year.vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  - 10.times do |index|
                    %option{value: "#{index + 19}"}= "#{index + 19}"
                  -# <i class="fas fa-chevron-down"></i>
              .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year__age
                年
          .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year__age__security
            .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year__age__security__security-code
              セキュリティコード
            .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want
              必須
            = text_field_tag "cvc", "", class: "cvc .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year__age__security__security-code__security-flame", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
            .vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year__age__security__security-code__security-flame__security-backnum
              カード裏面の番号とは？
          #card_token.vacuum__wide-box__entry-header__entry-box__entry-form__entry-register__want__card-num__crest__expiration__period-days__period-mm__period-month__period-yy__period-year__age__security__security-code__security-flame__security-backnum__entry-submit
            = submit_tag "追加する", id: "token_submit"

app/views/credit/show.html.haml
.Credit-Wrapper
  %p.Credit-Wrapper__title= "クレジットカード情報"
  .Credit-Wrapper__form
    %span.charge-errors
    .Register-Inner

      .Register-Inner__form
        %span.Register-Inner__label= "カード番号: "
        %span.Register-Inner__number
          = "**** **** ****" + @customer_card.last4

      .Register-Inner__select
        %span.Register-Inner__label= "有効期限: "
        %span.Register-Inner__expire
          - exp_month = @customer_card.exp_month.to_s
          - exp_year = @customer_card.exp_month.to_s
          = exp_month + "/" + exp_year
      .actions
        = form_tag(delete_credit_index_path, method: :post, id: 'charge-form', name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: ""}
          %button.register-member 削除する