config/routes.rb
Rails.application.routes.draw do
  get 'credit/show'
  devise_for :users, controllers: {seessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'accounts', to: 'users/registrations#new_account'
    post 'accounts', to: 'users/registrations#create_account'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items, only: [:index]
  get 'items/sell'
  resources :users, only: [:show, :edit, :update]
  resources :items do
    collection do #最終的にmemberに切り替える
      get :confirmation

      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :homes, only: [:new]
  resources :credit, only: [:new, :show, :destroy] do
    collection do
      post :pay
      post :delete
      get :show
      get :buy
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :description
    validates :price
    validates :fee_id
    validates :status_id
    validates :owner_area
    validates :shipping_id
  end

  validates :price, numericality:{only_integer: true,  message: "は半角数字のみ入力してください"}, allow_blank: true

  #image紐付け先のバリデーション
  validates_associated :images
  validates :images, presence: { message: 'は１枚以上添付してください'}
  #ここまでimageのバリデーション
  belongs_to :category

  
  #選択肢作成
  enum status: {
    "新品": "新品",
    "未使用に近い": "未使用に近い",
    "目立った傷等はない": "目立った傷等はない",
    "軽い傷がある": "軽い傷がある",
    "汚れが多い": "汚れが多い",
    "かなり汚れている": "かなり汚れている",
  }
  enum shipping: {
    "1~2日": "1~2日",
    "2~3日": "2~3日",
    "3~4日": "3~4日",
    "4~5日": "4~5日",
    "一週間以上": "一週間以上",
  }
  enum shipping_fee: {
    "送料込み(出品者負担)": "送料込み(出品者負担)",
    "着払い(購入者負担)": "着払い(購入者負担)"
  }


  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  validates :category_id, presence: true
  validates :category, presence: true, if: -> { category_id.present? }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :destroy]
  def index
  end

  def sell
  end

  def new
    @item = Item.new
    @item.images.new
    @category_parent_array = Category.where(ancestry: nil)
  end

  def get_category_children
    @category_children = Category.find_by(id: "#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path(@item)
    else
      @item.images.new
      @category_parent_array = Category.where(ancestry: nil)
      render :new
    end
  end

  def confirmation
  end

  def show
    @user_name = User.find(@item.seller_id).nickname
    @owner_place = User.find(@item.seller_id).address.prefecture.name
    @brand = Brand.find(@item.id).brand_name
    @category_name = Category.find(@item.category_id).category_name
    @shipping = Shipping.find(@item.seller_id).name
    @status = Status.find(@item.status_id).name
    @fee = Fee.find(@item.fee_id).name
  end


  def edit
  end
  
  def destroy
    @item.destroy
  end

  def item_params
    params.require(:item).permit(:name, :price, :description, :status_id, :fee_id, :owner_area, :shipping_id, :seller_id, :category_id, :brand_id, images_attributes: [:image, :_destroy, :id])
  end

  def set_item
    @item = Item.find(params[:id])
  end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_bottom_content.html.haml
.middle-main
  .middle-main__pickupContainer
    .middle-main__pickupContainer__head
      ピックアップカテゴリー
      .middle-main__pickupContainer__head__productBox
        .middle-main__pickupContainer__head__productBox__productHead
          新規投稿ページ
        .middle-main__pickupContainer__head__productBox__productHead__productLists
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/IMG_9072.jpeg", size: "220x150", alt: "image1", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                ee
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  1000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                (税込)
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/a007.png", size: "220x150", alt: "image2", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                product3
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  30000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                (税込）
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/a004.png", size: "220x150", alt: "image3", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                product2
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  20000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                (税込）
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/a001.png", size: "220x150", alt: "image4", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                product1
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  10000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                （税込）
    .middle-main__pickupContainer__head
      ピックアップブランド
      .middle-main__pickupContainer__head__productBox
        .middle-main__pickupContainer__head__productBox__productHead
          アーカイバ
        .middle-main__pickupContainer__head__productBox__productHead__productLists
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/IMG_9072.jpeg", size: "220x150", alt: "image1", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                ee
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  1000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                (税込)
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/a007.png", size: "220x150", alt: "image2", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                product3
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  30000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                (税込）
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/a004.png", size: "220x150", alt: "image3", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                product2
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  20000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                (税込）
          .middle-main__pickupContainer__head__productBox__productHead__productLists__productList
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image
              = image_tag("/images/a001.png", size: "220x150", alt: "image4", class: "productList-image")
            .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name
                product1
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price
                .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__font
                  10000円
                  = icon('fas', 'fa-star')
              .middle-main__pickupContainer__head__productBox__productHead__productLists__productList__productList-image__productList-body__name__price__tax
                （税込）
  
  .middle-main__appBanner
    = image_tag("/images/bg-appBanner-pict.jpg", size: "#", alt: "haikei", class: "appBanner")
    .middle-main__appBanner__inner
      .middle-main__appBanner__inner__inner-title
        だれでもかんたん、人生を変えるフリマアプリ
      .middle-main__appBanner__inner__inner-title__inner-text
        今すぐ無料ダウンロード！
      .middle-main__appBanner__inner__inner-title__inner-text__inner-icon
        = image_tag("/images/applestore.svg", size: "180x53", alt: "appletag", class: "inner-icon")
        = image_tag("/images/googleplay.svg", size: "180x53", alt: "gogletag", class: "inner-icon")

  .middle-main__top-footer
    .middle-main__top-footer__case
      .middle-main__top-footer__case__break
        .middle-main__top-footer__case__break__footer-title
          FURIMAについて
        .middle-main__top-footer__case__break__footer-title__outline
          会社概要（運営会社）
        .middle-main__top-footer__case__break__footer-title__outline__privacy
          プライバシーポリシー
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms
          FURIMA利用規約
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant
          ポイントに関する特約
      .middle-main__top-footer__case__break
        .middle-main__top-footer__case__break__footer-title
          FURIMAを見る
        .middle-main__top-footer__case__break__footer-title__outline
          カテゴリー一覧
        .middle-main__top-footer__case__break__footer-title__outline__privacy
          ブランド一覧
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant__footer-logo
          = image_tag("/images/logo-white.png", size: "", alt: "furima", class: "footer-logo")
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant__footer-logo__bottom-logo
          © FURIMA
      .middle-main__top-footer__case__break
        .middle-main__top-footer__case__break__footer-title
          ヘルプ＆ガイド
        .middle-main__top-footer__case__break__footer-title__outline
          FURIMAガイド
        .middle-main__top-footer__case__break__footer-title__outline__privacy
          FURIMAロゴ利用ガイドライン
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms
          お知らせ
          
  .middle-main__purchaseBtn
    .middle-main__purchaseBtn__purchase-text
      出品する
      .middle-main__purchaseBtn__purchase-text__purchase-icon
    = link_to image_tag("/images/icon_camera.svg", size: "54x54", alt: "furima", class: "purchase-icon"), new_item_path

app/views/items/_top_content.html.haml
.Header
  .Header__inner
    .Header__logo-search
      .Header__logo
        = link_to image_tag("/images/logo.png", alt: "furima", class: "Header__logo-inner"), "#"
      .Search
        = form_with(url: "#", method: :get, class: "Header__search-inner") do |f|
          .Search__box
            =f.text_field :keyword, placeholder: "キーワードから探す", class: "Search__field"
            =f.label :keyword do
              = f.submit "検索",style: "display: none"
              = icon('fas', 'search', class: "Search__icon")
    .Header__nav
      .Header__items
        .Header__category
          %ul.Dropdwn
            %li.Dropdwn__list-top
              カテゴリー
              %ul.Dropdwn__menu
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    レディース
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    メンズ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    ベビー・キッズ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    インテリア・住まい・小物
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    本・音楽・ゲーム
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    おもちゃ・ホビー・グッズ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    コスメ・香水・美容
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    家電・スマホ・カメラ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    スポーツ・レジャー
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    ハンドメイド
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    チケット
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    自動車・オートバイ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    その他
          = link_to "/", class: "Dropdwn__list-top" do
            ブランド
        .Header__user-log
          - if user_signed_in?
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "Header__list-right"
          - else
            = link_to "ログイン", new_user_session_path, class: "Header__list-right"
            = link_to "新規登録画面", new_user_registration_path, class: "Header__list-right"
.Main
  = image_tag("/images/bg-mainVisual-pict_pc.jpg", size: "1445x550", alt: "フリマアプリ", class: "Main__img")
  .Main__inner
    .Main__box
      %h1.Main__head 人生を変えるフリマアプリ
      %p.Main__subtitle FURIMAはだれでもかんたんに出品・購入できる
      %p フリマアプリです
    .Main__download
      = link_to image_tag("/images/applestore.svg", alt: "apple", class: "Main__apple"), "#"
      = link_to image_tag("/images/googleplay.svg", alt: "google", class: "Main__google"), "#"

.Middle
  %h1.Middle__title FURIMAが選ばれる3つの理由
  .Middle__inner
    .Middle__card
      = image_tag("/images/pict-reason-01.jpg", size: "300x300", alt: "フリマアプリ", class: "Middle__img")
      %span.Middle__num 1
      .Middle__box
        .Middle__text
          %span.Middle__span>3分
          ですぐに出品
        .Middele__text-inner スマホで入力するだけで簡単に出品できる！
    .Middle__card
      = image_tag("/images/pict-reason-02.jpg", size: "300x300", alt: "フリマアプリ", class: "Middle__img")
      %span.Middle__num 2
      .Middle__box
        .Middle__box-inner
        .Middle__text
          %span.Middle__span>シンプル
          で使いやすい
        .Middele__text-inner めんどくさい入力は必要なく、検索も購入もスムーズ！
    .Middle__card
      = image_tag("/images/pict-reason-03.jpg", size: "300x300", alt: "フリマアプリ", class: "Middle__img")
      %span.Middle__num 3
      .Middle__box
        .Middle__text
          手数料
          %span.Middle__span 業界最安
        .Middele__text-inner 最大3%でお得に出品&購入！

.Section
  = image_tag("/images/bg-topMiddleDl-pict.jpg", size: "1445x450", alt: "フリマアプリ", class: "Section__img")
  .Section__inner
    .Section__box
      %h1.Section__head 会員数日本一位
      %p.Section__subtitle FURIMAは、フリマアプリで最も人気。
      %p 出品・購入回数も業界最多です！
      %p ほしかったあの商品に出会えるかもしれません。
    .Section__download
      = link_to image_tag("/images/applestore.svg", alt: "apple", class: "Section__apple"), "#"
      = link_to image_tag("/images/googleplay.svg", alt: "google", class: "Section__google"), "#"

.Middle
  %h1.Middle__title FURIMAの特徴
  .Middle__inner
    .Middle__card
      = image_tag("/images/icon-01.png", size: "250x300", alt: "フリマアプリ", class: "Middle__img")
      .Middle__box
        .Middle__text 簡単に売り買いできる
        .Middele__text-inner スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    .Middle__card
      = image_tag("/images/icon-03.png", size: "250x300", alt: "フリマアプリ", class: "Middle__img")
      .Middle__box
        .Middle__box-inner
        .Middle__text 売上金は即日振込みに対応
        .Middele__text-inner 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
    .Middle__card
      = image_tag("/images/icon-04.png", size: "250x300", alt: "フリマアプリ", class: "Middle__img")
      .Middle__box
        .Middle__text 様々な支払いに対応
        .Middele__text-inner お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/items/destroy.html.haml
商品を削除しました。
= link_to "トップ", root_path

app/views/items/index.html.haml
.wrapper
  = render partial: 'top_content'
  = render partial: 'bottom_content'

app/views/items/show.html.haml
.detail
  .detail__header
    .Header
      = link_to image_tag("/images/logo.png", alt: "furima", class: "Header__logo-inner"), "#"
      .Search
        = form_with(url: "#", method: :get, class: "Header__search-inner") do |f|
          .Search__box
            =f.text_field :keyword, placeholder: "キーワードから探す", class: "Search__field"
            =f.label :keyword do
              = f.submit "検索",style: "display: none"
              = icon('fas', 'search', class: "Search__icon")
    .Header__nav
      .Header__items
        .Header__category
          %ul.Dropdwn
            %li.Dropdwn__list-top
              カテゴリー
              %ul.Dropdwn__menu
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    レディース
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    メンズ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    ベビー・キッズ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    インテリア・住まい・小物
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    本・音楽・ゲーム
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    おもちゃ・ホビー・グッズ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    コスメ・香水・美容
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    家電・スマホ・カメラ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    スポーツ・レジャー
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    ハンドメイド
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    チケット
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    自動車・オートバイ
                %li
                  = link_to '/',class: "Dropdwn__list" do
                    その他
          = link_to "/", class: "Dropdwn__list-top" do
            ブランド
        .Header__user-log
          = link_to "/", class: "Header__list-right" do
            ログイン
          = link_to "/", class: "Header__list-right" do
            新規登録画面
  .details
    %ul.details_lists
      %li.details_list
        = link_to '/',class: "detail_list" do
          メンズ
      %li.details_list
        = link_to '/',class: "fa" do
          > 
      %li.details_list
        = link_to '/',class: "detail_list" do
          ジャケットアウター
      %li.details_list
        = link_to '/',class: "fa" do
          > 
      %li.details_list
        = link_to '/',class: "detail_list" do
          ノーカラージャケット
      %li.details_list
        = link_to '/',class: "fa" do
          >       
      %li.details_list
        = link_to '/',class: "detail_list" do
          = @item.name
.mainWarrapp  
  .detail__main
    .detail_main__box
      .detail__title 
        %h1 
          = @item.name
          - if user_signed_in? && @item.seller_id == current_user.id
            %span
              = link_to "商品の削除", item_path(@item.id), method: :delete, class: "detail_delete"
            %span
              = link_to "商品の編集", edit_item_path, class: "detail_delete"
      .detail__image
        %ul.other__images
          - @item.images.each do |image|
            %li.image
              = image_tag image.image_url,class: "image_show"
              %ul.image_sub
                %il.image_sub_show
                  = image_tag image.image_url,class: "image_sub_show_small"
      .items__price
        %h2 
          = "#{@item.price}円"
        %p (税込)送料込み 
      - if user_signed_in? && @item.seller_id != current_user.id
        %span
          = link_to "購入する", confirmation_items_path, class: "items_buy"
      .item__text
        = @item.description
      %table.item_details
        %tr.item_details
          %th.item_details__lists
            出品者
          %td.detail__content
            = @user_name
        %tr.item_details
          %th.item_details__lists
            カテゴリー
          %td.detail__content
            = link_to "" ,class: "item__list" do
              = @category_name
        %tr.item_details
          %th.item_details__lists
            ブランド
          %td.detail__content
            = @brand
        %tr.item_details
          %th.item_details__lists
            商品の状態
          %td.detail__content
            = @status
        %tr.item_details
          %th.item_details__lists
            配送料の負担
          %td.detail__content
            = @fee
        %tr.item_details
          %th.item_details__lists
            配送元地域
          %td.detail__content
            = @owner_place
        %tr.item_details
          %th.item_details__lists
            発送日の目安
          %td.detail__content
            = @shipping
      .pagecontents
        %ul.pagecontent
          %li.pagecontent__list
            = link_to '/',class: "left_text" do
              ★お気に入り
          %li.pagecontent__list
            = link_to '/',class: "right_text" do
              🏴不適切な商品の通報
    //後半の実装のために一時的にコメントアウト
    -# .main_chat__form
    -#   = form_with model: @user, url: user_session_path, local: true do |f|
    -#     = f.password_field :text, placeholder: "", class: "Form_commet"
    -#   .Form_other
    -#     相手のことを考え丁寧なコメントを心がけましょう。
    -#     不愉快な言葉遣いなどは利用制限や退会処分となることがあります。
    -#   .Form__botton
    -#     = form_with model: @user, url: user_session_path, local: true do |f|
    -#       = f.submit "コメントする", class: 'commentBtn'
    .other__chat
      %ul.other__items
        %li.other__left
          = link_to '/',class: "before" do
            < 前の商品
        %li.other__right
          = link_to '/',class: "after" do
            後ろの商品＞
    .category1_items
      = link_to '/',class: "category1_form" do
        メンズをもっと見る

.middle-main
  .middle-main__pickupContainer
  .middle-main__appBanner
    = image_tag("/assets/bg-appBanner-pict", size: "#", alt: "haikei", class: "appBanner")
    .middle-main__appBanner__inner
      .middle-main__appBanner__inner__inner-title
        だれでもかんたん、人生を変えるフリマアプリ
      .middle-main__appBanner__inner__inner-title__inner-text
        今すぐ無料ダウンロード！
      .middle-main__appBanner__inner__inner-title__inner-text__inner-icon
        = image_tag("/assets/applestore.svg", size: "180x53", alt: "appletag", class: "inner-icon")
        = image_tag("/assets/googleplay.svg", size: "180x53", alt: "gogletag", class: "inner-icon")

  .middle-main__top-footer
    .middle-main__top-footer__case
      .middle-main__top-footer__case__break
        .middle-main__top-footer__case__break__footer-title
          FURIMAについて
        .middle-main__top-footer__case__break__footer-title__outline
          会社概要（運営会社）
        .middle-main__top-footer__case__break__footer-title__outline__privacy
          プライバシーポリシー
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms
          FURIMA利用規約
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant
          ポイントに関する特約
      .middle-main__top-footer__case__break
        .middle-main__top-footer__case__break__footer-title
          FURIMAを見る
        .middle-main__top-footer__case__break__footer-title__outline
          カテゴリー一覧
        .middle-main__top-footer__case__break__footer-title__outline__privacy
          ブランド一覧
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant__footer-logo
          = image_tag("/assets/logo-white.png", size: "", alt: "furima", class: "footer-logo")
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms__covenant__footer-logo__bottom-logo
          © FURIMA
      .middle-main__top-footer__case__break
        .middle-main__top-footer__case__break__footer-title
          ヘルプ＆ガイド
        .middle-main__top-footer__case__break__footer-title__outline
          FURIMAガイド
        .middle-main__top-footer__case__break__footer-title__outline__privacy
          FURIMAロゴ利用ガイドライン
        .middle-main__top-footer__case__break__footer-title__outline__privacy__terms
          お知らせ
          
  .middle-main__purchaseBtn
    .middle-main__purchaseBtn__purchase-text
      出品する
      .middle-main__purchaseBtn__purchase-text__purchase-icon
    = link_to image_tag("/assets/icon_camera.svg", size: "54x54", alt: "furima", class: "purchase-icon"), new_item_path